require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
require('./governance/runtime').validateRuntime();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const path = require('path');
const { sequelize } = require('./models');
const app = express();
const PORT = process.env.BACKEND_PORT || 4001;
const origins = String(process.env.CLIENT_URL || 'http://localhost:3001').split(',').map((v) => v.trim());
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: (origin, cb) => !origin || origins.includes(origin) ? cb(null, true) : cb(new Error('Origin not allowed')), credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
const mounts = { auth:'auth', 'fish-stocks':'fishStock', 'feed-records':'feedOptimization', 'water-quality':'waterQuality', 'harvest-plans':'harvestPlan', regulatory:'regulatory', species:'species', ponds:'ponds', 'feed-inventory':'feedInventory', employees:'employees', equipment:'equipment', diseases:'diseaseDetection', 'growth-records':'growthAnalysis', financial:'financial', suppliers:'suppliers', weather:'weatherAnalysis', sensors:'sensors', 'vision-disease':'visionDisease', 'ai-results':'aiResults', sustainability:'sustainability', integrations:'integrations', 'agentic-farm-manager':'agenticFarmManager', 'cv-disease-monitor':'cvDiseaseMonitor', 'realtime-water-optim':'realtimeWaterOptim', 'traceability-chain':'traceabilityChain', 'equipment-maintenance':'equipmentMaintenance', 'sustainability-cert':'sustainabilityCertification', 'market-price-forecast':'marketPriceForecast', 'stocking-permit-planner':'stockingPermitPlanner' };
Object.entries(mounts).forEach(([mount, name]) => app.use(`/api/${mount}`, require(`./routes/${name}`)));
app.use('/api', require('./routes/agenticFarm'));
app.use('/api/governed-workflow', require('./governance/router'));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.use((err, _req, res, _next) => { console.error('Request failed:', err.message); res.status(err.status || 500).json({ error: 'Internal server error' }); });
app.use((_req, res) => res.status(404).json({ error: 'Route not found' }));
async function start() { await sequelize.authenticate(); app.listen(PORT, () => console.log(`Server running on port ${PORT}`)); }
if (require.main === module) start().catch((error) => { console.error('Startup failed:', error.message); process.exit(1); });
module.exports = app;
